version: '3.9'
services:
  node:
    image: server_node
    restart: always
    ports:
      - 80:5000
      - 5000:5000
      - 4000:4000
    volumes:
      - ./:/code
    links:
      - "mongo:mongo"
  mongo:
    image: mongo:5.0.5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: FindME
    volumes:
      - mongodb:/data/db
      - ./server/init-mongodb:/docker-entrypoint-initdb.d
      - ./server/init-mongodb/data:/tmp/data
volumes:
  mongodb:
    name: mongodb-FindME-data